### ISSUE TITLE
Treasury Wont Load

### ISSUE THREAD

**Issue by spmckinn** [arkein/Hearthstone-Treasury#3]
I am receiving the following error after trying to load Treasury in HDT.

System.MissingFieldException: Field not found: 'Hearthstone_Deck_Tracker.API.LogEvents.OnRachelleLogLine'.
   at Hearthstone_Treasury.HearthstoneTreasuryPlugin.OnLoad()
   at Hearthstone_Deck_Tracker.Plugins.PluginWrapper.Load() in C:\projects\hearthstone-deck-tracker\Hearthstone Deck Tracker\Plugins\PluginWrapper.cs:line 91

I've uninstalled and reinstalled, redownloaded and looked for the reset button mentioned in another post and can't find a way to get it to load. 

Any suggestions on how to fix it?

**Comment by arkein** [comment]
The plugin might be no longer compatible with the latest HDT, will check.

**Comment by arkein** [comment]
Tracked down the problem to renaming change in commit https://github.com/HearthSim/Hearthstone-Deck-Tracker/commit/2ef5980cef985d6fc2bcc28066aa2f0a6ffd5800#diff-bec4d34eb2fd6608e37b67ce8c03f5a5
Will release updated plugin version soon.

**Comment by arkein** [comment]
@spmckinn I've released plugin v0.5.0, please test.

**Comment by spmckinn** [comment]
@arkein plugin loaded fine, but will not auto track gold from wins and dailies for some reason. Still troubleshooting for errors on my end. I unblocked all the files and clicked reset and im running HTD on admin. Is there something I am overlooking?

**Comment by arkein** [comment]
@spmckinn No, that's something that I've overlooked.
It wasn't a simple renaming, the HS no longer writes Rachelle.log which I'm reading for gold rewards.
The rewards are still appearing in Achievements.log, but HDT has no API for that (yet).

**Comment by arkein** [comment]
@spmckinn I've released plugin v0.5.1, please test (with HDT 1.8.0+).
